## Data Exploration / Understanding

In [3]:
# view the three datasets
import pandas as pd
import sys
from pathlib import Path

sys.path.append(str(Path("..").resolve()))

TRANSCRIPTS_PATH = Path("..") / "data" / "transcripts_cleaned.csv" # not using this in this notebook

In [6]:
transcript_df = pd.read_csv(TRANSCRIPTS_PATH)
print(transcript_df.shape)
transcript_df.head()

(157, 6)

,Record-ID,Class,Transcript_PFT,Transcript_CTD,Transcript_SFT,Label
0,Process-rec-001,MCI,"people, partner, plate, platter, pants, porter...",NaN,"<pause_medium> giraffe, kangaroo, lion, tiger,...",1
1,Process-rec-002,MCI,"<pause_short> pipe, plane, people <pause_mediu...",<pause_medium> there’s a lad stood on the stoo...,"<pause_short> dogs, cats, birds <pause_short> ...",1
2,Process-rec-003,MCI,"um <pause_short> purple, pale, placid <pause_s...","<pause_medium> um, the picture is of a kitchen...","cow, bull, ewe, ram, chicken, goose, um <sigh>...",1
3,Process-rec-004,MCI,plank <pause_short> pool <pause_short> swimmin...,"a mother presumably, or a fe, an adult female ...",um <pause_short> impala <pause_short> er cheet...,1
4,Process-rec-005,MCI,"it’s er pillock, er post box, er pyracanthas, ...","‘50s style er scene of domestic um confusion, ...","dog, cat, giraffe, wallaby, kangaroo, tortoise...",1

In [9]:
DATASET_PATH = Path("..") / "data" / "dementia_data.csv"
dataset_df = pd.read_csv(DATASET_PATH)
print(dataset_df.shape)
dataset_df.head()

(157, 25)

,Record-ID,TrainOrDev,Class,Gender,Age,Converted-MMSE,Transcript_PFT,Transcript_CTD,Transcript_SFT,Class_label,...,filler_count,token_count,type_count,type_token_ratio,ma_ttr,brunets_index,content_density,repetitions,sentence_count,average_words_per_sentence
0,Process-rec-001,train,MCI,1,62,25.0,"Pat: People, partner, plate, platter, pants, p...",NaN,"Pat: (3 seconds) Giraffe, kangaroo, lion, tige...",1,...,1,0,0,0.000000,0.000000,0.000000,0.000000,{},0,0.000000
1,Process-rec-002,dev,MCI,1,61,25.0,"Pat: (1 second) Pipe, plane, people (5 seconds...",Pat: (4 seconds) There’s a lad stood on the st...,"Pat: (1 second) Dogs, cats, birds (1 second) m...",1,...,2,76,46,0.605263,1.000000,1.487174,0.421053,"{'there': 2, 's': 7, 'a': 5, 'stood': 2, 'on':...",5,15.200000
2,Process-rec-003,train,MCI,0,62,29.0,"Pat: Um (1 second) purple, pale, placid (1 sec...","Pat: (3 seconds) Um, the picture is of a kitch...","Pat: Cow, bull, ewe, ram, chicken, goose, um (...",1,...,6,150,84,0.560000,0.995495,1.620714,0.433333,"{'the': 10, 'is': 5, 'of': 2, 'a': 10, 'there'...",7,21.428571
3,Process-rec-004,dev,MCI,0,67,29.0,Pat: Plank (1 second) pool (1 second) swimming...,"Pat: A mother presumably, or a fe, an adult fe...",Pat: Um (1 second) impala (1 second) er cheeta...,1,...,4,162,88,0.543210,1.000000,1.675909,0.425926,"{'a': 5, 'or': 2, 'an': 4, 'adult': 3, 'female...",4,40.500000
4,Process-rec-005,train,MCI,1,65,27.0,"Pat: It’s er pillock, er post box, er Pyracant...",Pat: ‘50s style er scene of domestic um confus...,"Pat: Dog, cat, giraffe, wallaby, kangaroo, tor...",1,...,4,44,36,0.818182,1.000000,1.057222,0.500000,"{'s': 3, 'of': 4, 'the': 3, 'and': 2}",1,44.000000

In [10]:
# all the 25 columns
print(dataset_df.columns)

Index(['Record-ID', 'TrainOrDev', 'Class', 'Gender', 'Age', 'Converted-MMSE',
       'Transcript_PFT', 'Transcript_CTD', 'Transcript_SFT', 'Class_label',
       'total_seconds', 'Parentheses_Content', 'CTD_Cleaned', 'found_fillers',
       'filler_list', 'filler_count', 'token_count', 'type_count',
       'type_token_ratio', 'ma_ttr', 'brunets_index', 'content_density',
       'repetitions', 'sentence_count', 'average_words_per_sentence'],
      dtype='object')

In [13]:
# first row of dementia_data
print(dataset_df.head(1))

         Record-ID TrainOrDev Class  Gender Age  Converted-MMSE  \
0  Process-rec-001      train   MCI       1  62            25.0

                                      Transcript_PFT Transcript_CTD  \
0  Pat: People, partner, plate, platter, pants, p...            NaN

                                      Transcript_SFT  Class_label  ...  \
0  Pat: (3 seconds) Giraffe, kangaroo, lion, tige...            1  ...

   filler_count token_count type_count type_token_ratio ma_ttr  brunets_index  \
0             1           0          0              0.0    0.0            0.0

   content_density  repetitions  sentence_count  average_words_per_sentence
0              0.0           {}               0                         0.0

[1 rows x 25 columns]

In [30]:
# imports
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [24]:
# let's make a copy of the dataset_df and split into train_X, test_X, train_Y, text_Y
# let's also decide which features to include and which features to change

df = dataset_df.copy()
# y = numeric class label (0 = HC, 1 = MCI, 2 = Dementia)
y = df["Class_label"]

# fix error in Age and convert from Sting to Numeric
df["Age"] = df["Age"].replace("66*", "66")
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

# combine transcripts into one text field
df["all_text"] = (
    df["Transcript_PFT"].fillna("") + " " +
    df["Transcript_SFT"].fillna("") + " " +
    df["Transcript_CTD"].fillna("")
)

# choose numeric features you want to include
numeric_features = [
    "Converted-MMSE",
    "Age",
    "filler_count",
    "token_count",
    "type_count",
    "type_token_ratio",
    "ma_ttr",
    "brunets_index",
    "content_density",
    "sentence_count",
    "average_words_per_sentence",
]

categorical_features = ["Gender"]

# dropped: Record-ID, TrainOrDev, Class, repetitions (maybe engineer this later)

In [23]:
# See if any NaN or incorrect numeric values

for col in numeric_features:
    print(f"\nColumn: {col}")
    print(df[col].unique())

Column: Converted-MMSE
[25.         29.         27.         26.         27.36231884 28.
 19.         22.         23.         30.         20.         24.        ]

Column: Age
['62' '61' '67' '65' '83' '68' '77' '56' '60' '72' '74' '66' '45' '75'
 '70' '80' '71' '69' '73' '86' '51' '79' '55' '52' '57' '82' '76' '78'
 '37' '23' '49' '64' '24' '36' '30' '59' '63' '94' '84' '50' '87' '66*'
 '58' '27']

Column: Gender
[1 0 2]

Column: filler_count
[ 1  2  6  4  3  7  5  9  8 40 10 14 26 13 12 21 18 11 16 39 22 17 15 29
 28 38]

Column: token_count
[  0  76 150 162  44 122 219 100 184 307 109 161 351 224 188 143  66 134
 306  52  69 222 135  80 334 130  83 212  92  98 115 152 283  81 243 239
 180 247  77 138 406 268  49 118  71 145 119 482 198 156 221 269 160 149
 167 140 129  90 127 237 117 120 128 309 213 133 267  48  47 197  65 216
 113 257 200 114  87 193 154 111 340 187 123 179 367  63 225  78  26  82
 182 254  86 391 195 311 166 317 168  88  22  25  61 206 176  95  67  39
 153  74 233  94 421 141 164  12 121 485 207 170 189 275 447 236  96  54
 242]

Column: type_count
[  0  46  84  88  36  78 119  57  80 136  53  81 150 101  93  85  45  79
 147  37 111  76  54 145  67 100  55  64  65  94 132 117  98 110  47 107
 157  43 131  39  90  69  51  75  71 168  96 103 126  74  72  50  73 109
 102  34  40  99  48 105  59  89 138  77 149 104  61  22  97 121 167  95
 139  91  17  20  44  60  56  26 153  12  42 169 123 191 129  63  35]

Column: type_token_ratio
[0.         0.60526316 0.56       0.54320988 0.81818182 0.63934426
 0.543379   0.57       0.43478261 0.44299674 0.48623853 0.50310559
 0.42735043 0.45089286 0.49468085 0.59440559 0.6969697  0.68181818
 0.58955224 0.48039216 0.71153846 0.65217391 0.5        0.56296296
 0.675      0.43413174 0.51538462 0.63855422 0.47169811 0.59782609
 0.65306122 0.56521739 0.61842105 0.4664311  0.56790123 0.45679012
 0.48953975 0.54444444 0.44534413 0.61038961 0.56914894 0.55072464
 0.38669951 0.51807229 0.48880597 0.79591837 0.4787234  0.58474576
 0.66233766 0.57692308 0.66197183 0.51724138 0.59663866 0.6
 0.34854772 0.48484848 0.56410256 0.46606335 0.46840149 0.4625
 0.63087248 0.38323353 0.51428571 0.55813953 0.55       0.55555556
 0.51181102 0.42616034 0.48717949 0.53333333 0.5703125  0.60833333
 0.35275081 0.47887324 0.57142857 0.5093633  0.70833333 0.85106383
 0.50253807 0.48765432 0.37827715 0.73846154 0.48611111 0.52212389
 0.49027237 0.505      0.5877193  0.44949495 0.5862069  0.51813472
 0.56302521 0.51298701 0.47747748 0.40588235 0.5828877  0.62601626
 0.55865922 0.40599455 0.68253968 0.46222222 0.61538462 0.67777778
 0.84615385 0.56097561 0.53296703 0.47637795 0.53488372 0.42710997
 0.44694534 0.54819277 0.34700315 0.48214286 0.60227273 0.77272727
 0.8        0.72131148 0.58914729 0.45754717 0.7        0.47087379
 0.56818182 0.56842105 0.59701493 0.66666667 0.53691275 0.48913043
 0.49673203 0.6147541  0.68918919 0.45922747 0.62765957 0.36342043
 0.54887218 0.5035461  0.55487805 1.         0.58677686 0.53153153
 0.5915493  0.34845361 0.4589372  0.57446809 0.49411765 0.53968254
 0.44727273 0.42729306 0.6557377  0.54661017 0.65625    0.64814815
 0.45867769]

Column: ma_ttr
[0.         1.         0.9954955  0.99444444 0.98979592 0.99450549
 0.99672131 0.99065421 0.98951782 0.98376313 0.996997   0.99641577
 0.99763593 0.99479167 0.984375   0.98737374 0.99342105 0.98
 0.98939394 0.9924812  0.99196787 0.98697917 0.98353909 0.98730159
 0.99259259 0.99115044 0.99288256 0.98755187 0.98452883 0.99812734
 0.98911565 0.98666667 0.99283154 0.97524752 0.99588477 0.99462366
 0.99425287 0.99111111 0.98958333 0.98368298 0.997151   0.99375
 0.98639456 0.98268398 0.99543379 0.99156118 0.99546485 0.91111111
 0.98792271 0.9816273  0.98106061 0.976      0.98723404 0.99717514
 0.9815418  0.98894155 0.99745547 0.99496855 0.99275362 0.99145299
 0.99791667 0.98490566 0.98412698 0.98598131 0.92792793 0.97777778
 0.98653199 0.99404762 0.97959184 0.98431373 0.97435897 0.98684211
 0.99082569 0.99506903 0.98018018 0.99724518 0.9890411  0.99453552
 0.99252616 0.97222222 0.99166667 0.99074074 0.99470899 0.99143102
 0.99309154 0.98597627 0.99593496 0.99153439 0.98594378 0.99475066
 0.98850575 0.98888889 0.98717949 0.99836601 0.99616858 0.97948718
 0.99267399 0.98675497 0.99537037 0.98845599 0.98806683 0.99176955
 0.97368421 0.96918768 0.98776758 0.97584541 0.99033816 0.97723577
 0.98217469 0.995116   0.99325843 0.9858156  0.9875    ]

Column: brunets_index
[0.         1.48717391 1.62071429 1.67590909 1.05722222 1.39910256
 1.67533613 1.58938596 2.135      2.09235294 1.89160377 1.82265432
 2.175      2.05282178 1.85650538 1.51735294 1.26978261 1.30166667
 1.53120253 1.91663265 1.24040541 1.36833333 1.835      1.61131579
 1.31648148 2.13844828 1.77529851 1.40103774 1.955      1.50772727
 1.36625    1.60423077 1.45202128 1.97893939 1.59586957 2.02418919
 1.87773504 1.67173469 2.08045455 1.47329787 1.59200935 1.65078947
 2.42098726 1.76523256 1.88080153 1.09141026 1.92388889 1.54514493
 1.34480392 1.56833333 1.3456383  1.76833333 1.51105634 1.50166667
 2.70404762 1.8975     1.60772727 1.98063107 1.96992063 1.99716216
 1.42010638 2.444375   1.77944444 1.62666667 1.65318182 1.635
 1.78884615 2.18153465 1.88763158 1.71       1.58842466 1.47883562
 2.66986239 1.92323529 1.585      1.79823529 1.24676471 1.01
 1.82489899 1.88563291 2.47856436 1.18916667 1.89214286 1.75025424
 1.87468254 1.81519802 1.53649254 2.0597191  1.54088235 1.765
 1.6111194  1.78436709 1.92933962 2.29876812 1.55059633 1.4324026
 1.625      2.29808725 1.30011628 1.99846154 1.46       1.31040984
 1.01681818 1.6176087  1.71128866 1.93417355 1.70456522 2.17631737
 2.07241007 1.65917582 2.71681818 1.90907407 1.49537736 1.12911765
 1.085      1.22136364 1.53236842 2.02056701 1.26357143 1.95871134
 1.595      1.59425926 1.51       1.335      1.6975     1.87944444
 1.84815789 1.46166667 1.28598039 2.01257009 1.42822034 2.58663399
 1.65691781 1.82091549 1.6371978  0.835      1.53922535 1.71635593
 1.52547619 2.70482249 2.01394737 1.57574074 1.85880952 1.68794118
 2.07077236 2.17531414 1.36       1.66445736 1.35880952 1.37785714
 2.01518018]

Column: content_density
[0.         0.42105263 0.43333333 0.42592593 0.5        0.40163934
 0.40639269 0.43       0.45108696 0.42996743 0.44954128 0.38509317
 0.46153846 0.39732143 0.40957447 0.38461538 0.45454545 0.40909091
 0.43283582 0.43137255 0.44230769 0.42028986 0.41441441 0.4
 0.4125     0.41317365 0.39230769 0.40963855 0.37264151 0.41304348
 0.42857143 0.40869565 0.38815789 0.40636042 0.41975309 0.39506173
 0.40167364 0.42777778 0.40890688 0.44155844 0.45212766 0.36956522
 0.37931034 0.34939759 0.42910448 0.40816327 0.39361702 0.41525424
 0.40769231 0.42253521 0.3862069  0.39834025 0.43939394 0.45512821
 0.40723982 0.44237918 0.38125    0.43624161 0.40718563 0.41085271
 0.46       0.38888889 0.44094488 0.44725738 0.41025641 0.425
 0.4453125  0.49166667 0.37540453 0.4084507  0.43071161 0.47916667
 0.42553191 0.41624365 0.42322097 0.39351852 0.42477876 0.42412451
 0.41       0.4122807  0.3908046  0.44041451 0.37815126 0.4025974
 0.40540541 0.46176471 0.40106952 0.41463415 0.38547486 0.46321526
 0.41269841 0.40888889 0.43589744 0.41111111 0.57692308 0.40243902
 0.45604396 0.38582677 0.37209302 0.43734015 0.40512821 0.40192926
 0.39759036 0.41009464 0.39880952 0.375      0.44       0.36065574
 0.43410853 0.44565217 0.45762712 0.44811321 0.475      0.43203883
 0.41477273 0.40298507 0.48717949 0.36912752 0.43478261 0.45
 0.44444444 0.40983607 0.43243243 0.43347639 0.40380048 0.39772727
 0.38345865 0.39716312 0.3902439  0.38016529 0.42342342 0.32394366
 0.43298969 0.39130435 0.41489362 0.38823529 0.37818182 0.4541387
 0.45081967 0.39830508 0.48148148 0.42975207]

Column: repetitions
['{}'
 "{'there': 2, 's': 7, 'a': 5, 'stood': 2, 'on': 3, 'the': 5, 'to': 2, 'cookie': 2, '.': 4, 'washing': 2, 'she': 2, 'and': 4, 'is': 2, 'plate': 2}"
 "{'the': 10, 'is': 5, 'of': 2, 'a': 10, 'there': 2, 's': 8, 'mum': 3, 'and': 5, 'it': 3, '.': 6, 'to': 7, 'meanwhile': 2, 'going': 2, 'on': 5, 'floor': 2, 'him': 2, 'his': 3, 'sister': 2, 'he': 2, 'just': 2, 'cookie': 2, 'stool': 2, 'about': 2}"
 "{'a': 5, 'or': 2, 'an': 4, 'adult': 3, 'female': 3, 'and': 7, 'children': 2, 'male': 2, 'child': 4, 'the': 10, 'is': 8, 'with': 3, 'open': 3, 'she': 2, 's': 3, 'to': 7, 'her': 3, '.': 4, 'on': 3, 'of': 3, 'stool': 2, 'he': 5, 'cookie': 3, 'has': 2, 'one': 2, 'hand': 3, 'in': 2, 'standing': 2}"
 "{'s': 3, 'of': 4, 'the': 3, 'and': 2}"
 "{'a': 5, 'in': 2, 'the': 11, 'kitchen': 3, 'but': 2, 'her': 2, 'children': 2, 'to': 3, 'cookie': 2, 'jar': 2, 'behind': 2, 'and': 4, 'obviously': 2, 'can': 2, 'them': 2, 'is': 4, 'as': 2, 'it': 3, '.': 5, 'boy': 2, 'girl': 2, 's': 2}"
 "{'and': 7, 'drying': 2, 'the': 17, 'sink': 2, 'is': 7, 'overflowing': 2, '.': 6, 'it': 6, 'there': 4, 's': 7, 'to': 2, 'her': 5, 'children': 2, 'i': 2, 'they': 2, 're': 2, 'are': 2, 'doing': 2, 'cookie': 2, 'jar': 2, 'by': 3, 'up': 2, 'on': 3, 'of': 5, 'a': 5, 'stool': 2, 'he': 2, 'back': 2, 'looks': 4, 'as': 3, 'if': 3, 'has': 2, 'in': 2, 'because': 2, 'but': 2, 'lid': 2, 'that': 2, 't': 2, 'window': 2, 'which': 2, 'some': 2, 'kind': 2, 'garden': 2, 'you': 2, 'kitchen': 2}"
 "{'a': 8, 'is': 3, 'the': 4, 'and': 4, '.': 7, 'out': 3, 'cookie': 2, 'jar': 2, 'it': 5, 'looks': 5, 'he': 5, 's': 6, 'there': 2}"
 "{'the': 23, 'is': 5, 'a': 14, 'kitchen': 2, 'in': 3, 'house': 2, '.': 9, 'there': 6, 's': 10, 'lady': 3, 'standing': 2, 'at': 3, 'sink': 3, 'plate': 2, 'with': 2, 'two': 2, 'boy': 3, 'and': 8, 'girl': 2, 'on': 5, 'stool': 2, 'to': 2, 'cupboard': 3, 'curtains': 2, 'window': 4, 'of': 2, 'got': 3, 'shoes': 3, 't-shirt': 2, 'socks': 2}"
 "{'the': 30, 'a': 17, 'mother': 5, 'and': 18, 'boy': 3, 'girl': 3, 'her': 5, 'in': 6, 'kitchen': 3, 'there': 4, 'are': 4, '.': 9, 'is': 5, 'on': 5, 'trying': 3, 'to': 10, 'up': 4, 'cookie': 2, 'top': 3, 'shelf': 2, 'of': 4, 's': 13, 'left': 2, 'hand': 3, 'from': 3, 'by': 2, 'sink': 2, 'which': 2, 'overflowing': 2, 'with': 5, 'water': 3, 'it': 6, 'all': 2, 'going': 2, 'she': 3, 'window': 3, 'leading': 2, 'looks': 2, 'be': 2, 'got': 2, 'wearing': 4, 'dress': 2, 'or': 2}"
 "{'s': 12, 'a': 2, 'boy': 3, 'on': 4, 'and': 9, 'he': 3, 'looks': 2, 'over': 2, 'trying': 2, 'to': 4, 'get': 4, 'the': 14, 'left': 2, 'is': 2, '.': 2, 'she': 2, 'what': 2, 'floor': 2, 'just': 2}"
 "{'there': 7, 'is': 8, 'a': 11, 'overflowing': 2, 'sink': 3, '.': 7, 'on': 6, 'the': 13, 'her': 5, 'and': 5, 'two': 3, 'are': 2, 'one': 2, 'that': 2, 's': 5, 'standing': 2, 'floor': 2, 'cookies': 2, 'cookie': 2, 'jar': 2, 'in': 2, 'has': 2, 'out': 2, 'of': 5, 'window': 3}"
 "{'.': 21, 'it': 17, 'looks': 7, 'a': 14, 'bit': 2, 'there': 10, 'are': 8, 'of': 7, 'happening': 2, 'that': 2, 't': 3, 'be': 4, 'the': 23, 'woman': 3, 'is': 11, 'in': 7, 'sink': 3, 'child': 2, 'about': 4, 'cookie': 2, 'jar': 2, 'and': 7, 'to': 6, 'or': 5, 'out': 2, 'window': 2, 'drying': 2, 'dishes': 3, 's': 11, 'either': 3, 'seems': 3, 'her': 2, 'brother': 2, 'who': 3, 'i': 7, 'presumably': 2, 'with': 2, 'curtains': 2, 'on': 4, 'see': 4, 'kind': 2, 'what': 3, 'else': 2, 'plate': 2, 'maybe': 2, 'house': 2, 'door': 2, 'also': 4, 'have': 2, 'm': 2, 'summer': 2, 'people': 2}"
 "{'there': 7, 's': 21, 'a': 8, 'up': 3, 'to': 3, 'cookie': 3, 'jar': 3, 'in': 3, 'the': 12, 'cupboard': 2, 'i': 4, 't': 2, 'he': 8, 'be': 2, 'doing': 3, 'it': 5, 'and': 10, 'on': 2, 'stool': 2, 'gon': 3, 'na': 3, 'off': 2, '.': 8, 'his': 2, 'who': 2, 'wanted': 2, 'her': 3, 'one': 2, 'was': 2, 'she': 5, 'about': 2, 'that': 7, 'by': 2, 'or': 2, 'over': 2, 'garage': 2, 'have': 2, 'question': 2, 'oth': 2, 'yeah': 3}"
 "{'a': 7, 'woman': 2, 'the': 19, 'machine': 2, 'is': 5, 'sink': 2, 'onto': 2, 'floor': 2, 'and': 9, 'her': 3, '.': 5, 'male': 2, 'child': 2, 'stood': 2, 'on': 4, 'that': 5, 's': 10, 'to': 3, 'cookie': 2, 'out': 2, 'of': 5, 'something': 3, 'she': 3, 'side': 3, 'plate': 2, 'with': 2, 'already': 2, 'there': 3, 'two': 2, 'what': 2, 'be': 2, 'another': 3, 'window': 2, 'looks': 2, 'then': 2, 'it': 2, 'building': 2}"
 "{'s': 5, 'a': 8, 'lady': 2, 'her': 4, 'up': 2, 'she': 3, 'and': 6, 'the': 9, 'is': 3, 'out': 2, 'going': 2, 'floor': 2, 'on': 4, '.': 4, 'two': 2, 'to': 3, 'get': 2, 'he': 4, 'stool': 2, 'looks': 2, 'as': 2, 'if': 2, 'fall': 2, 't': 2, 'very': 2, 'his': 2, 'him': 2}"
 "{'and': 5, 'the': 4, 'is': 2, 'it': 3, 'looks': 3, 'they': 2, '.': 3, 'she': 2, 's': 4, 'kitchen': 2}"
 "{'a': 2, 'is': 3, 'standing': 2, 'on': 3, 'the': 4, 'and': 2, 's': 2, 'about': 2, 'to': 4, '.': 3, 'his': 3, 'she': 2, 'over': 2}"
 "{'i': 2, 'a': 4, 'the': 12, 'pots': 2, 'she': 3, 's': 11, 'and': 5, 'it': 3, '.': 4, 'two': 2, 'children': 2, 'in': 2, 'he': 2, 'obviously': 2, 'stood': 2, 'on': 3, 'stool': 2, 'is': 2, 'girl': 2, 'likely': 2, 'to': 4, 'cookie': 2, 'jar': 2, 'head': 2}"
 "{'a': 14, 'is': 11, 'the': 25, 'up': 3, 'she': 9, 's': 17, 'and': 5, '.': 15, 't': 2, 'left': 3, 'it': 5, 'that': 2, 'window': 3, 'there': 6, 'with': 3, 'of': 2, 'house': 2, 'or': 2, 'got': 4, 'at': 2, 'are': 5, 'on': 2, 'counter': 2, 'top': 2, 'two': 2, 'plate': 3, 'five': 2, 'in': 3, 'wearing': 3, 'shoes': 2, 'an': 2, 'hair': 2, 'her': 4, 'hand': 4, 'children': 2, 'one': 3, 'stool': 4, 'boy': 2, 'he': 6, 'toppling': 2, 'down': 2, 'to': 2, 'girl': 2, 'his': 3, 'socks': 2, 'short': 2}"
 "{'s': 2, 'on': 3, 'the': 3, 'three': 2, 'people': 2, 'one': 3, 'a': 4, 'boy': 2, 'and': 2, '.': 2}"
 "{'is': 5, 'a': 3, 'to': 3, 'out': 2, 'which': 2, 'about': 2, '.': 3, 'the': 7, 'sink': 2, 'water': 2, 'it': 2, 'and': 2, 's': 2}"
 "{'there': 6, 'are': 3, 'three': 2, 'in': 4, 'the': 18, 'picture': 2, 'a': 11, 'woman': 2, 'boy': 2, 'on': 3, 'that': 4, 's': 8, 'and': 9, 'he': 3, 'taking': 2, 'cookies': 2, 'jar': 3, 'girl': 2, 'standing': 2, 'to': 4, 'out': 2, 'cookie': 4, 'just': 2, 'or': 4, '.': 10, 'sink': 2, 'is': 8, 'two': 2, 'window': 4, 'be': 3, 'has': 2, 'bars': 2, 'i': 2, 'one': 3, 'it': 2, 'his': 2, 'may': 2}"
 "{'looks': 2, 'mum': 3, 'is': 4, 'the': 15, 'but': 3, 'on': 3, 'she': 5, 's': 4, 'as': 3, 'and': 4, 'kitchen': 2, '.': 5, 'about': 2, 'at': 2, 'other': 2, 'of': 3, 'get': 3, 'trying': 2, 'to': 3, 'into': 2, 'cookie': 3, 'jar': 2, 'in': 2, 'falling': 2, 'over': 2, 'a': 2}"
 "{'up': 2, 'the': 6, 'is': 2, '.': 3, 'there': 3, 'a': 6, 's': 4, 'on': 2, 'stool': 2, 'and': 4, 'also': 2, 'window': 2}"
 "{'do': 3, 'you': 5, 'want': 2, 'to': 9, 'now': 2, 're': 3, 'not': 5, 'it': 6, 's': 15, 'a': 12, 'all': 2, 'of': 3, 'things': 3, 'are': 2, '.': 11, 'there': 3, 'mother': 3, 'and': 16, 'but': 3, 'be': 4, 'very': 3, 'as': 2, 'cookie': 5, 'jar': 3, 'the': 27, 'is': 7, 'woman': 3, 'up': 2, 'she': 9, 'distracted': 2, 'water': 2, 'from': 2, 'drying': 2, 'at': 4, 'paying': 3, 'attention': 3, 'over': 3, 'floor': 2, 'children': 4, 'on': 6, 'stool': 4, 'in': 2, 'he': 3, 'about': 2, 'fall': 2, 'her': 2, 't': 3, 'window': 2, 'can': 4, 'plate': 2, 'they': 4, 'doing': 2, 'got': 2, 'i': 3}"
 "{'there': 9, 's': 12, 'a': 11, 'lady': 2, 'the': 8, 'running': 2, 'and': 6, '.': 9, 'on': 3, 'which': 2, 'is': 2, 'some': 3, 'out': 2, 'of': 3, 'jar': 2, 'plate': 2, 'they': 2}"
 "{'there': 3, 's': 6, 'a': 4, 'mum': 2, 'and': 3, 'the': 7, 'up': 2, '.': 5, 'she': 2, 'out': 2, 'to': 2, 'is': 2, 'cookies': 2, 'dunno': 2}"
 "{'oth': 4, 'you': 2, '.': 12, 'but': 2, 'can': 4, 'it': 10, 'a': 8, 'bit': 2, 'yeah': 2, 'i': 5, 'got': 2, 'to': 4, 'the': 17, 'on': 5, 't': 2, 'oh': 4, 'jar': 3, 'that': 4, 's': 14, 'and': 10, 'he': 4, 'about': 2, 'in': 2, 'of': 3, 'him': 2, 'at': 2, 'kitchen': 2, 'sink': 3, 'washing': 2, 'pots': 2, 'spilling': 2, 'water': 2}"
 "{'there': 3, 'is': 6, 'a': 8, 'of': 3, 'housewife': 2, 's': 3, '.': 5, 'the': 8, 'water': 2, 'on': 2, 'are': 2, 'in': 3, 'standing': 2, 'to': 2}"
 "{'s': 6, 'a': 6, '.': 5, 'who': 2, 'on': 3, 'of': 2, 'the': 9, 'and': 2, 'appears': 2, 'to': 3, 'be': 2, 'sink': 2, 'is': 2, 'there': 2}"
 "{'two': 2, 'one': 2, 's': 10, 'on': 4, 'a': 6, 'and': 4, 'it': 2, 'falling': 2, '.': 7, 'there': 6, 'wife': 2, 'the': 7, 'window': 3, 'open': 2, 'looks': 3, 'is': 2, 'are': 2, 'cupboard': 2}"
 "{'a': 9, 'mother': 3, 'and': 7, 'children': 2, 'in': 3, 'the': 12, 'is': 6, 'sink': 2, '.': 5, 'are': 3, 'about': 3, 'on': 2, 's': 4, 'to': 2, 'cookie': 2, 'beside': 2, 'him': 2, 'up': 2, 'for': 2, 'window': 2, 'some': 2, 'there': 2, 'plate': 2}"
 "{'it': 5, 'to': 4, 'be': 4, 'a': 20, 'standing': 4, 'the': 17, 'sink': 5, 'washing': 2, '.': 9, 'she': 4, 's': 12, 'left': 3, 'on': 4, 'and': 10, 'is': 5, 'which': 3, 'in': 8, 'front': 3, 'of': 6, 'looks': 3, 'could': 2, 'or': 8, 'her': 4, 'there': 2, 'plate': 2, 'are': 2, 'two': 2, 'girl': 3, 'got': 3, 'short': 3, 'stool': 2, 'over': 2, 'i': 4, 'think': 2, 'very': 3, 'he': 5, 'his': 3, 'cookie': 2, 'jar': 2, 'cookies': 2, 'take': 2, 'with': 2}"
 "{'in': 4, 'the': 12, 'a': 4, 'on': 2, 'stool': 3, 'and': 4, 'is': 3, '.': 5, 'there': 3, 's': 4, 'lad': 2}"
 "{'the': 29, 'mother': 4, 'is': 6, 'to': 4, 'up': 5, 'plate': 2, 'she': 4, 's': 14, 'because': 3, 'water': 2, 'over': 3, 'side': 2, 'of': 2, 'sink': 2, '.': 10, 'there': 4, 'be': 5, 'it': 6, 'looks': 5, 'might': 4, 'a': 10, 'meanwhile': 2, 'boy': 2, 'from': 2, 'cookie': 2, 'in': 3, 'second': 2, 'stool': 2, 'he': 2, 'as': 3, 'though': 3, 'reaching': 2, 'for': 2, 'yeah': 3, 'and': 3, 'laughing': 2, 'also': 2, 'maybe': 2, 'or': 2, 'with': 2, 'way': 2, 'dressed': 2, 'are': 2}"
 "{'there': 8, 's': 6, 'a': 12, 'lady': 2, 'the': 27, 'sink': 2, 'and': 6, 'is': 11, 'with': 2, 'water': 2, 'going': 2, 'floor': 3, 'she': 3, 'standing': 2, 'in': 3, 'on': 5, '.': 9, 'to': 5, 'cookies': 3, 'cookie': 3, 'jar': 3, 'but': 2, 'it': 4, 'looks': 2, 'are': 4, 'which': 3, 'one': 2, 'of': 3, 'be': 2, 'window': 2, 'has': 2, 'curtains': 2, 'side': 2, 'house': 2, 'units': 2, 'some': 3, 'have': 2, 'handles': 2}"
 "{'a': 7, 'of': 4, 'washing': 2, 'up': 3, 'in': 3, 'the': 14, 'where': 2, 'is': 5, 'side': 2, 'she': 5, 's': 7, 'to': 2, '.': 7, 'looking': 2, 'from': 2, 'children': 3, 'are': 5, 'behind': 2, 'her': 3, 'by': 2, 'looks': 2, 'things': 2, 'cookie': 2, 'jar': 2, 'there': 3, 'girl': 2, 'and': 5, 'boy': 2, 'little': 2, 'has': 2, 'stool': 2, 'his': 2, 'on': 2, 'left': 2, 't': 2, 'doing': 2}"
 "{'the': 27, 'is': 13, 'a': 8, 'coming': 2, 'of': 2, 'sink': 2, 'she': 7, 's': 11, 'left': 3, 'on': 5, 'and': 11, 'it': 4, 'over': 3, 'floor': 2, 'gon': 2, 'na': 2, 'get': 2, '.': 12, 'children': 2, 'are': 5, 'in': 2, 'cupboard': 2, 'going': 2, 'for': 2, 'cookie': 2, 'boy': 2, 'stool': 2, 'he': 3, 'up': 3, 'girl': 2, 'at': 2, 'hand': 2, 'open': 2, 'can': 2, 'there': 4, 'curtains': 2, 'window': 2, 'garden': 2, 'looks': 2, 'with': 2, 'two': 2, 'short': 2, 'wearing': 5, 'dress': 2, 'shoes': 2}"
 "{'a': 9, 'at': 2, 'sink': 2, 'the': 8, 'up': 3, 's': 4, 'and': 3, '.': 3, 'children': 2, 'in': 2, 'cupboard': 2, 'kitchen': 2}"
 "{'there': 5, 's': 9, 'a': 10, 'in': 4, 'with': 2, 'of': 3, 'the': 16, 'from': 2, 'sink': 2, 'while': 2, '.': 9, 'out': 2, 'is': 2, 'open': 2, 'are': 3, 'quite': 2, 'boy': 3, 'about': 2, 'to': 5, 'fall': 2, 'stool': 2, 'he': 2, 'cupboard': 2, 'and': 5, 'down': 2, 'can': 2, 'girl': 2, 'socks': 2, 'be': 2, 'got': 2, 'one': 2}"
 "{'is': 6, 'in': 3, 'the': 20, '.': 4, 'a': 2, 'who': 2, 's': 4, 'and': 7, 'on': 4, 'her': 3, 'as': 3, 'she': 2, 'seems': 2, 'to': 7, 'be': 3, 'going': 2, 'cookie': 2, 'boy': 2, 'stool': 2, 'he': 2}"

In [34]:
# X = text + numeric columns + cat (gender)
X = df[[text_feature] + numeric_features + categorical_features]

In [35]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y,
)

## Preprocessing: TF-IDF for text, scaling for numeric

In [36]:
text_feature = "all_text"

text_transformer = TfidfVectorizer(
    ngram_range=(1, 2),   # unigrams + bigrams
    min_df=2,             # ignore super-rare words
    max_features=10000,   # cap vocab size (tweak if you want)
)

numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown="ignore")

preprocess = ColumnTransformer(
    transformers=[
        ("text", text_transformer, text_feature),
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features),
    ],
    remainder="drop",
)

## K-Fold

In [49]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_scores = cross_val_score(
    clf,
    X_train,          # IMPORTANT: only training data
    y_train,
    cv=cv,
    scoring="f1_macro"   # or "accuracy", "f1_weighted", etc.
)

print("CV scores:", cv_scores)
print("Mean CV:", cv_scores.mean(), "±", cv_scores.std())

CV scores: [0.63729246 0.31800766 0.5        0.34188034 0.4040404 ]
Mean CV: 0.4402441747269334 ± 0.11689885266282973

In [43]:
# Standard deviation = 0.1169 which means that my model performance swings a LOT depending on the split

## Creating the Logistic Regression Model + Training It

In [50]:
log_reg = LogisticRegression(
    solver="lbfgs",           # liblinear or lbfgs # good for multinomial
    max_iter=1000,
    class_weight="balanced",  # handle HC/MCI/Dementia imbalance
    n_jobs=-1,                # use all cores
)
clf = Pipeline(steps=[
    ("preprocess", preprocess),
    ("logreg", log_reg),
])

In [51]:
clf.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('text',
                                                  TfidfVectorizer(max_features=10000,
                                                                  min_df=2,
                                                                  ngram_range=(1,
                                                                               2)),
                                                  'all_text'),
                                                 ('num', StandardScaler(),
                                                  ['Converted-MMSE', 'Age',
                                                   'filler_count',
                                                   'token_count', 'type_count',
                                                   'type_token_ratio', 'ma_ttr',
                                                   'brunets_index',
                                                   'content_density',
                                                   'sentence_count',
                                                   'average_words_per_sentence']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender'])])),
                ('logreg',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    n_jobs=-1))])

## Evaluating the Model

In [52]:
y_pred = clf.predict(X_test)

print("Classification report:")
print(classification_report(y_test, y_pred))

print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))

Classification report:
              precision    recall  f1-score   support

           0       0.72      0.76      0.74        17
           1       0.56      0.42      0.48        12
           2       0.20      0.33      0.25         3

    accuracy                           0.59        32
   macro avg       0.49      0.50      0.49        32
weighted avg       0.61      0.59      0.60        32

Confusion matrix:
[[13  3  1]
 [ 4  5  3]
 [ 1  1  1]]

## Optional: K Fold training and Evaluating on best Fold

In [53]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

param_grid = {
    "logreg__C": [0.01, 0.1, 1, 10],
    "logreg__solver": ["lbfgs"],
}

grid = GridSearchCV(
    clf,
    param_grid,
    cv=cv,
    scoring="f1_macro",   # or "accuracy"
    n_jobs=-1,
)

grid.fit(X_train, y_train)

print("Best params:", grid.best_params_)
print("Best CV score:", grid.best_score_)
best_clf = grid.best_estimator_

Best params: {'logreg__C': 10, 'logreg__solver': 'lbfgs'}
Best CV score: 0.46359172581816477

In [54]:
y_pred = best_clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83        17
           1       0.64      0.58      0.61        12
           2       0.00      0.00      0.00         3

    accuracy                           0.69        32
   macro avg       0.48      0.49      0.48        32
weighted avg       0.66      0.69      0.67        32